import type { DocumentPreset } from "@/lib/types";

/**
 * 🇮🇳 India Document & ID Card Preset Catalog
 * 
 * IMPORTANT: This catalog does NOT assume a single physical size for all cards.
 * Verified official sizes are marked with sizeSource: "OFFICIAL" and verificationStatus: "verified".
 * Formats without reliable hard dimensions use sizeSource: "VERIFY_BEFORE_USE" or "STANDARD_DERIVED".
 */

export const PRESET_REGISTRY: DocumentPreset[] = [
    // ─── 1. GOVERNMENT IDENTITY (CARDS) ─────────

    {
        id: "aadhaar-pvc",
        name: "Aadhaar PVC Card",
        category: "government_identity",
        widthMm: 86,
        heightMm: 54, // Official CR80 standard mandated by UIDAI for PVC
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "OFFICIAL",
        sourceReference: "UIDAI PVC Printing Specification",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["aadhaar", "pvc", "card", "uidai", "id-1"],
    },
    {
        id: "pan-card",
        name: "PAN Card",
        category: "government_identity",
        widthMm: 85.60,
        heightMm: 53.98,
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "STANDARD_DERIVED",
        verificationStatus: "configurable",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["pan", "nsdl", "uti", "tax", "pvc"],
    },
    {
        id: "driving-licence",
        name: "Driving Licence (Smart Card)",
        category: "government_identity",
        widthMm: 85.6,
        heightMm: 54.02,
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "OFFICIAL",
        sourceReference: "MoRTH Smart Card Specifications (Tolerance ±2mm)",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["dl", "driving", "rto", "transport", "smartcard"],
    },
    {
        id: "voter-epic-old",
        name: "Voter ID / EPIC (Old Legacy)",
        category: "government_identity",
        widthMm: 90,
        heightMm: 70,
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "HISTORICAL",
        sourceReference: "Election Commission of India (Legacy Format)",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["voter", "epic", "eci", "election", "legacy"],
    },
    {
        id: "voter-epic-new",
        name: "Voter ID / EPIC (New PVC)",
        category: "government_identity",
        widthMm: 84, // or 85.6
        heightMm: 50, // or 54
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "OFFICIAL",
        sourceReference: "ECI Color PVC Guidelines",
        verificationStatus: "configurable",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["voter", "epic", "eci", "election", "pvc", "new"],
    },

    // ─── 2. GOVERNMENT DOCUMENTS (A4/PRINT FORMATS) ───

    {
        id: "aadhaar-letter",
        name: "Aadhaar Letter (Full Page)",
        category: "government_document",
        widthMm: 210,
        heightMm: 297, // A4 page
        orientation: "portrait",
        sides: "single",
        sizeSource: "COMMON_PRINT_FORMAT",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "free",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: false,
        supportsPerspectiveCorrection: true,
        tags: ["aadhaar", "letter", "print", "document", "a4"],
    },
    {
        id: "generic-certificate",
        name: "Government Certificate (Birth, Caste, etc)",
        category: "government_document",
        widthMm: 210,
        heightMm: 297,
        orientation: "portrait",
        sides: "single",
        sizeSource: "COMMON_PRINT_FORMAT",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: false,
        supportsPerspectiveCorrection: true,
        tags: ["birth", "death", "caste", "income", "domicile", "certificate", "a4"],
    },
    {
        id: "passport-document",
        name: "Passport Document (Scan/PDF)",
        category: "government_document",
        // 125 x 88 mm is the B7 physical booklet size, but usually printed on A4
        widthMm: 125,
        heightMm: 88,
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "OFFICIAL",
        sourceReference: "ICAO Doc 9303 (TD3 Format)",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["passport", "booklet", "icao", "scan", "travel"],
    },

    // ─── 3. FINANCIAL / BANKING ─────────

    {
        id: "generic-bank-card",
        name: "Bank / Financial Card (Generic)",
        category: "financial",
        widthMm: 85.60,
        heightMm: 53.98,
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "ISO_STANDARD",
        sourceReference: "ISO/IEC 7810 ID-1",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["atm", "debit", "credit", "rupay", "visa", "mastercard"],
    },

    // ─── 4. EDUCATION ─────────

    {
        id: "student-id-card",
        name: "Student / School ID Card",
        category: "education",
        orientation: "portrait", // Generally vertical
        sides: "front-back",
        sizeSource: "VERIFY_BEFORE_USE", // highly variable
        verificationStatus: "configurable",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["school", "college", "university", "student", "id", "vertical"],
    },

    // ─── 5. HEALTHCARE & SCHEMES ─────────

    {
        id: "ayushman-card",
        name: "Ayushman Bharat / PM-JAY Card",
        category: "healthcare",
        widthMm: 85.6,
        heightMm: 53.98, // commonly printed on ID-1 or A4 layout
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "VERIFY_BEFORE_USE",
        verificationStatus: "configurable",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["ayushman", "health", "pmjay", "medical"],
    },

    // ─── 6. POSTAL DOCUMENTS ─────────

    {
        id: "india-post-postcard",
        name: "India Post - Postcard",
        category: "postal",
        widthMm: 140,
        heightMm: 90,
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "OFFICIAL",
        sourceReference: "India Post Prescribed Dimensions",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "free",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: false,
        tags: ["post", "postal", "postcard", "mail"],
    },

    // ─── 7. PHOTO PRESETS ─────────

    {
        id: "passport-photo-standard",
        name: "Standard Passport Photo (Indian)",
        category: "photo",
        widthMm: 35,
        heightMm: 45,
        orientation: "portrait",
        sides: "single",
        sizeSource: "OFFICIAL",
        sourceReference: "Indian Passport Photo Guidelines",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "fixed-ratio",
        defaultPaper: "4x6",
        supportsBatch: true,
        supportsFrontBack: false,
        supportsPerspectiveCorrection: false,
        tags: ["photo", "passport", "35x45", "face"],
    },
    {
        id: "visa-photo-us",
        name: "US Visa Photo (2x2 inch)",
        category: "photo",
        widthMm: 51, // 2 inches
        heightMm: 51,
        orientation: "portrait",
        sides: "single",
        sizeSource: "OFFICIAL",
        sourceReference: "US State Department",
        verificationStatus: "verified",
        defaultDpi: 300,
        cropMode: "fixed-ratio",
        defaultPaper: "4x6",
        supportsBatch: true,
        supportsFrontBack: false,
        supportsPerspectiveCorrection: false,
        tags: ["photo", "visa", "2x2", "us"],
    },

    // ─── 8. TRANSPORT & REGISTRATION ─────────

    {
        id: "rc-smart-card",
        name: "RC Smart Card (Vehicle)",
        category: "transport",
        widthMm: 85.6,
        heightMm: 54, // Generally ID-1 format
        orientation: "landscape",
        sides: "front-back",
        sizeSource: "VERIFY_BEFORE_USE",
        verificationStatus: "configurable",
        defaultDpi: 300,
        cropMode: "perspective",
        defaultPaper: "A4",
        supportsBatch: true,
        supportsFrontBack: true,
        supportsPerspectiveCorrection: true,
        tags: ["rc", "vehicle", "rto", "registration", "car", "bike"],
    },
];
