import type { Template } from "@/lib/types";

const now = new Date().toISOString();

/**
 * 🇮🇳 India Document & ID Card Preset Catalog
 */
export const BUILT_IN_TEMPLATES: Template[] = [
  // ─── 1. GOVERNMENT IDENTITY (CARDS) ─────────
  {
    id: "aadhaar-pvc",
    name: "Aadhaar PVC Card",
    category: "government_identity",
    width: 86,
    height: 54, // Official CR80 standard mandated by UIDAI for PVC
    unit: "mm",
    aspectRatio: 86 / 54,
    cropSettings: { aspectRatio: 86 / 54 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "OFFICIAL",
    sourceReference: "UIDAI PVC Printing Specification",
    verificationStatus: "verified",
    sides: "front-back",
    tags: ["aadhaar", "pvc", "uidai", "id-1"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pan-card",
    name: "PAN Card",
    category: "government_identity",
    width: 85.60,
    height: 53.98,
    unit: "mm",
    aspectRatio: 85.6 / 53.98,
    cropSettings: { aspectRatio: 85.6 / 53.98 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "STANDARD_DERIVED",
    verificationStatus: "configurable",
    sides: "front-back",
    tags: ["pan", "nsdl", "uti", "tax", "pvc"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "driving-licence",
    name: "Driving Licence (Smart Card)",
    category: "government_identity",
    width: 85.6,
    height: 54.02,
    unit: "mm",
    aspectRatio: 85.6 / 54.02,
    cropSettings: { aspectRatio: 85.6 / 54.02 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "OFFICIAL",
    sourceReference: "MoRTH Smart Card Specifications (Tolerance ±2mm)",
    verificationStatus: "verified",
    sides: "front-back",
    tags: ["dl", "driving", "rto", "transport"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "voter-epic-old",
    name: "Voter ID / EPIC (Old Legacy)",
    category: "government_identity",
    width: 90,
    height: 70,
    unit: "mm",
    aspectRatio: 90 / 70,
    cropSettings: { aspectRatio: 90 / 70 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "HISTORICAL",
    sourceReference: "Election Commission of India (Legacy Format)",
    verificationStatus: "verified",
    sides: "front-back",
    tags: ["voter", "epic", "eci", "election", "legacy"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "voter-epic-new",
    name: "Voter ID / EPIC (New PVC)",
    category: "government_identity",
    width: 84, // Approximate newer ECI format
    height: 50,
    unit: "mm",
    aspectRatio: 84 / 50,
    cropSettings: { aspectRatio: 84 / 50 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "OFFICIAL",
    sourceReference: "ECI Color PVC Guidelines",
    verificationStatus: "configurable",
    sides: "front-back",
    tags: ["voter", "epic", "eci", "election", "pvc", "new"],
    createdAt: now,
    updatedAt: now,
  },

  // ─── 2. GOVERNMENT DOCUMENTS (A4) ───
  {
    id: "aadhaar-letter",
    name: "Aadhaar Letter (Full Page)",
    category: "government_document",
    width: 210,
    height: 297, // A4 page
    unit: "mm",
    aspectRatio: 210 / 297,
    cropSettings: { aspectRatio: 210 / 297 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 0, verticalGap: 0, copies: 1 },
    isBuiltIn: true,
    sizeSource: "COMMON_PRINT_FORMAT",
    verificationStatus: "verified",
    sides: "single",
    tags: ["aadhaar", "letter", "a4"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "passport-document",
    name: "Passport Document (Scan/PDF)",
    category: "government_document",
    width: 125, // B7 size ID-3 standard
    height: 88,
    unit: "mm",
    aspectRatio: 125 / 88,
    cropSettings: { aspectRatio: 125 / 88 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 10, verticalGap: 10, copies: 2 },
    isBuiltIn: true,
    sizeSource: "OFFICIAL",
    sourceReference: "ICAO Doc 9303 (TD3 Format)",
    verificationStatus: "verified",
    sides: "front-back",
    tags: ["passport", "booklet", "icao", "scan", "travel"],
    createdAt: now,
    updatedAt: now,
  },

  // ─── 3. FINANCIAL / BANKING ─────────
  {
    id: "generic-bank-card",
    name: "Bank / Financial Card (Generic)",
    category: "financial",
    width: 85.60,
    height: 53.98,
    unit: "mm",
    aspectRatio: 85.6 / 53.98,
    cropSettings: { aspectRatio: 85.6 / 53.98 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "ISO_STANDARD",
    sourceReference: "ISO/IEC 7810 ID-1",
    verificationStatus: "verified",
    sides: "front-back",
    tags: ["atm", "debit", "credit", "rupay", "visa", "mastercard"],
    createdAt: now,
    updatedAt: now,
  },

  // ─── 4. EDUCATION ─────────
  {
    id: "student-id-card",
    name: "Student / School ID Card",
    category: "education",
    width: 54, // typical vertical card
    height: 85.6,
    unit: "mm",
    aspectRatio: 54 / 85.6,
    cropSettings: { aspectRatio: 54 / 85.6 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "VERIFY_BEFORE_USE",
    verificationStatus: "configurable",
    sides: "front-back",
    tags: ["school", "college", "university", "student", "id", "vertical"],
    createdAt: now,
    updatedAt: now,
  },

  // ─── 5. HEALTHCARE & SCHEMES ─────────
  {
    id: "ayushman-card",
    name: "Ayushman Bharat / PM-JAY Card",
    category: "healthcare",
    width: 85.6,
    height: 53.98,
    unit: "mm",
    aspectRatio: 85.6 / 53.98,
    cropSettings: { aspectRatio: 85.6 / 53.98 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "VERIFY_BEFORE_USE",
    verificationStatus: "configurable",
    sides: "front-back",
    tags: ["ayushman", "health", "pmjay", "medical"],
    createdAt: now,
    updatedAt: now,
  },

  // ─── 6. POSTAL DOCUMENTS ─────────
  {
    id: "india-post-postcard",
    name: "India Post - Postcard",
    category: "postal",
    width: 140,
    height: 90,
    unit: "mm",
    aspectRatio: 140 / 90,
    cropSettings: { aspectRatio: 140 / 90 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "OFFICIAL",
    sourceReference: "India Post Prescribed Dimensions",
    verificationStatus: "verified",
    sides: "front-back",
    tags: ["post", "postal", "postcard", "mail"],
    createdAt: now,
    updatedAt: now,
  },

  // ─── 7. PHOTO PRESETS ─────────
  {
    id: "passport-photo",
    name: "Standard Passport Photo (Indian)",
    category: "photo",
    width: 35,
    height: 45,
    unit: "mm",
    aspectRatio: 35 / 45,
    cropSettings: { aspectRatio: 35 / 45 },
    paperSettings: { id: "4x6", orientation: "portrait" },
    layoutSettings: { horizontalGap: 3, verticalGap: 3, copies: "auto" },
    isBuiltIn: true,
    sizeSource: "OFFICIAL",
    sourceReference: "Indian Passport Photo Guidelines",
    verificationStatus: "verified",
    sides: "single",
    tags: ["photo", "passport", "35x45", "face"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "visa-photo-us",
    name: "US Visa Photo (2x2 inch)",
    category: "photo",
    width: 2,
    height: 2,
    unit: "in",
    aspectRatio: 1,
    cropSettings: { aspectRatio: 1 },
    paperSettings: { id: "4x6", orientation: "portrait" },
    layoutSettings: { horizontalGap: 3, verticalGap: 3, copies: "auto" },
    isBuiltIn: true,
    sizeSource: "OFFICIAL",
    sourceReference: "US State Department",
    verificationStatus: "verified",
    sides: "single",
    tags: ["photo", "visa", "2x2", "us"],
    createdAt: now,
    updatedAt: now,
  },

  // ─── 8. TRANSPORT & REGISTRATION ─────────
  {
    id: "rc-smart-card",
    name: "RC Smart Card (Vehicle)",
    category: "transport",
    width: 85.6,
    height: 54,
    unit: "mm",
    aspectRatio: 85.6 / 54,
    cropSettings: { aspectRatio: 85.6 / 54 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    sizeSource: "VERIFY_BEFORE_USE",
    verificationStatus: "configurable",
    sides: "front-back",
    tags: ["rc", "vehicle", "rto", "registration", "car"],
    createdAt: now,
    updatedAt: now,
  },

  // ─── 9. GENERIC & CUSTOM PRESETS ─────────
  {
    id: "generic-id",
    name: "Generic ID Card (ISO-ID1)",
    category: "id-card",
    width: 85.6,
    height: 54,
    unit: "mm",
    aspectRatio: 85.6 / 54,
    cropSettings: { aspectRatio: 85.6 / 54 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: "auto" },
    isBuiltIn: true,
    sizeSource: "ISO_STANDARD",
    verificationStatus: "configurable",
    sides: "front-back",
    tags: ["generic", "id", "card", "iso"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "passport-a4-35",
    name: "Passport Photos on A4 (35 copies)",
    category: "layout",
    width: 35,
    height: 45,
    unit: "mm",
    aspectRatio: 35 / 45,
    cropSettings: { aspectRatio: 35 / 45 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 3, verticalGap: 3, copies: "auto" },
    isBuiltIn: true,
    sizeSource: "COMMON_PRINT_FORMAT",
    verificationStatus: "verified",
    sides: "single",
    createdAt: now,
    updatedAt: now,
  },
];

export function getBuiltInTemplate(id: string): Template | undefined {
  return BUILT_IN_TEMPLATES.find((t) => t.id === id);
}
