import type { Template } from "@/lib/types";

const now = new Date().toISOString();

export const BUILT_IN_TEMPLATES: Template[] = [
  {
    id: "passport-photo",
    name: "Passport Photo",
    category: "photo",
    width: 35,
    height: 45,
    unit: "mm",
    aspectRatio: 35 / 45,
    cropSettings: { aspectRatio: 35 / 45 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 3, verticalGap: 3, copies: "auto" },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "visa-photo",
    name: "Visa Photo",
    category: "photo",
    width: 25,
    height: 35,
    unit: "mm",
    aspectRatio: 25 / 35,
    cropSettings: { aspectRatio: 25 / 35 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 3, verticalGap: 3, copies: "auto" },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "stamp-photo",
    name: "Stamp Photo",
    category: "photo",
    width: 20,
    height: 25,
    unit: "mm",
    aspectRatio: 20 / 25,
    cropSettings: { aspectRatio: 20 / 25 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 2, verticalGap: 2, copies: "auto" },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "2x2-photo",
    name: "2×2 inch Photo",
    category: "photo",
    width: 2,
    height: 2,
    unit: "in",
    aspectRatio: 1,
    cropSettings: { aspectRatio: 1 },
    paperSettings: { id: "4x6", orientation: "portrait" },
    layoutSettings: { horizontalGap: 3, verticalGap: 3, copies: "auto" },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "passport-a4-35",
    name: "Passport Photos on A4 (35 copies)",
    category: "layout",
    width: 35,
    height: 45,
    unit: "mm",
    aspectRatio: 35 / 45,
    cropSettings: { aspectRatio: 35 / 45 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 3, verticalGap: 3, copies: "auto" },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "passport-4x6-8",
    name: "Passport Photos on 4×6 (8 copies)",
    category: "layout",
    width: 35,
    height: 45,
    unit: "mm",
    aspectRatio: 35 / 45,
    cropSettings: { aspectRatio: 35 / 45 },
    paperSettings: { id: "4x6", orientation: "portrait" },
    layoutSettings: { horizontalGap: 2, verticalGap: 2, copies: 8 },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "generic-id",
    name: "Generic ID Card",
    category: "id-card",
    width: 85.6,
    height: 54,
    unit: "mm",
    aspectRatio: 85.6 / 54,
    cropSettings: { aspectRatio: 85.6 / 54 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: "auto" },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "aadhaar",
    name: "Aadhaar Card",
    category: "id-card",
    width: 85.6,
    height: 54,
    unit: "mm",
    aspectRatio: 85.6 / 54,
    cropSettings: { aspectRatio: 85.6 / 54 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pan-card",
    name: "PAN Card",
    category: "id-card",
    width: 85.6,
    height: 54,
    unit: "mm",
    aspectRatio: 85.6 / 54,
    cropSettings: { aspectRatio: 85.6 / 54 },
    paperSettings: { id: "a4", orientation: "portrait" },
    layoutSettings: { horizontalGap: 5, verticalGap: 5, copies: 2 },
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  },
];

export function getBuiltInTemplate(id: string): Template | undefined {
  return BUILT_IN_TEMPLATES.find((t) => t.id === id);
}
